language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1

sudo: false

notifications:
  email: false

before_install:
    - chmod +x gradlew

script:
    - ./gradlew clean

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'