language: android
android:
  components:
    - android-24
    - build-tools-24.0.1
    - platform-tools
    - tools
    # Repos
    - extra-google-m2repository
    - extra-android-m2repository
    # Emulators
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-16
script:
    - ./gradlew clean
licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'