package de.tudarmstadt.informatik.tk.assistance.profiler.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "measurement".
*/
public class MeasurementDao extends AbstractDao<Measurement, Long> {

    public static final String TABLENAME = "measurement";

    /**
     * Properties of entity Measurement.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Voltage = new Property(1, Float.class, "voltage", false, "VOLTAGE");
        public final static Property Current = new Property(2, Float.class, "current", false, "CURRENT");
        public final static Property Power = new Property(3, Float.class, "power", false, "POWER");
        public final static Property AvailableMemory = new Property(4, Long.class, "availableMemory", false, "AVAILABLE_MEMORY");
        public final static Property TotalMemory = new Property(5, Long.class, "totalMemory", false, "TOTAL_MEMORY");
        public final static Property MemoryTotalPss = new Property(6, Long.class, "memoryTotalPss", false, "MEMORY_TOTAL_PSS");
        public final static Property CpuLoad = new Property(7, Float.class, "cpuLoad", false, "CPU_LOAD");
        public final static Property Timestamp = new Property(8, long.class, "timestamp", false, "TIMESTAMP");
    };


    public MeasurementDao(DaoConfig config) {
        super(config);
    }
    
    public MeasurementDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"measurement\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VOLTAGE\" REAL," + // 1: voltage
                "\"CURRENT\" REAL," + // 2: current
                "\"POWER\" REAL," + // 3: power
                "\"AVAILABLE_MEMORY\" INTEGER," + // 4: availableMemory
                "\"TOTAL_MEMORY\" INTEGER," + // 5: totalMemory
                "\"MEMORY_TOTAL_PSS\" INTEGER," + // 6: memoryTotalPss
                "\"CPU_LOAD\" REAL," + // 7: cpuLoad
                "\"TIMESTAMP\" INTEGER NOT NULL );"); // 8: timestamp
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_measurement__id ON measurement" +
                " (\"_id\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"measurement\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Measurement entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Float voltage = entity.getVoltage();
        if (voltage != null) {
            stmt.bindDouble(2, voltage);
        }
 
        Float current = entity.getCurrent();
        if (current != null) {
            stmt.bindDouble(3, current);
        }
 
        Float power = entity.getPower();
        if (power != null) {
            stmt.bindDouble(4, power);
        }
 
        Long availableMemory = entity.getAvailableMemory();
        if (availableMemory != null) {
            stmt.bindLong(5, availableMemory);
        }
 
        Long totalMemory = entity.getTotalMemory();
        if (totalMemory != null) {
            stmt.bindLong(6, totalMemory);
        }
 
        Long memoryTotalPss = entity.getMemoryTotalPss();
        if (memoryTotalPss != null) {
            stmt.bindLong(7, memoryTotalPss);
        }
 
        Float cpuLoad = entity.getCpuLoad();
        if (cpuLoad != null) {
            stmt.bindDouble(8, cpuLoad);
        }
        stmt.bindLong(9, entity.getTimestamp());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Measurement readEntity(Cursor cursor, int offset) {
        Measurement entity = new Measurement( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1), // voltage
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // current
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // power
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // availableMemory
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // totalMemory
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // memoryTotalPss
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7), // cpuLoad
            cursor.getLong(offset + 8) // timestamp
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Measurement entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVoltage(cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1));
        entity.setCurrent(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setPower(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setAvailableMemory(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setTotalMemory(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setMemoryTotalPss(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setCpuLoad(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
        entity.setTimestamp(cursor.getLong(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Measurement entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Measurement entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
