package de.tudarmstadt.informatik.tk.assistance.profiler.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "measurement".
 */
public class Measurement {

    private Long id;
    private Float power;
    private Long memory;
    private Float cpuLoad;
    private long timestamp;

    public Measurement() {
    }

    public Measurement(Long id) {
        this.id = id;
    }

    public Measurement(Long id, Float power, Long memory, Float cpuLoad, long timestamp) {
        this.id = id;
        this.power = power;
        this.memory = memory;
        this.cpuLoad = cpuLoad;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getPower() {
        return power;
    }

    public void setPower(Float power) {
        this.power = power;
    }

    public Long getMemory() {
        return memory;
    }

    public void setMemory(Long memory) {
        this.memory = memory;
    }

    public Float getCpuLoad() {
        return cpuLoad;
    }

    public void setCpuLoad(Float cpuLoad) {
        this.cpuLoad = cpuLoad;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

}
