package de.tudarmstadt.informatik.tk.assistance.profiler.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "measurement".
 */
public class Measurement {

    private Long id;
    private Float voltage;
    private Float current;
    private Float power;
    private Long availableMemory;
    private Long totalMemory;
    private Long memoryTotalPss;
    private Float cpuLoad;
    private long timestamp;

    public Measurement() {
    }

    public Measurement(Long id) {
        this.id = id;
    }

    public Measurement(Long id, Float voltage, Float current, Float power, Long availableMemory, Long totalMemory, Long memoryTotalPss, Float cpuLoad, long timestamp) {
        this.id = id;
        this.voltage = voltage;
        this.current = current;
        this.power = power;
        this.availableMemory = availableMemory;
        this.totalMemory = totalMemory;
        this.memoryTotalPss = memoryTotalPss;
        this.cpuLoad = cpuLoad;
        this.timestamp = timestamp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getVoltage() {
        return voltage;
    }

    public void setVoltage(Float voltage) {
        this.voltage = voltage;
    }

    public Float getCurrent() {
        return current;
    }

    public void setCurrent(Float current) {
        this.current = current;
    }

    public Float getPower() {
        return power;
    }

    public void setPower(Float power) {
        this.power = power;
    }

    public Long getAvailableMemory() {
        return availableMemory;
    }

    public void setAvailableMemory(Long availableMemory) {
        this.availableMemory = availableMemory;
    }

    public Long getTotalMemory() {
        return totalMemory;
    }

    public void setTotalMemory(Long totalMemory) {
        this.totalMemory = totalMemory;
    }

    public Long getMemoryTotalPss() {
        return memoryTotalPss;
    }

    public void setMemoryTotalPss(Long memoryTotalPss) {
        this.memoryTotalPss = memoryTotalPss;
    }

    public Float getCpuLoad() {
        return cpuLoad;
    }

    public void setCpuLoad(Float cpuLoad) {
        this.cpuLoad = cpuLoad;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

}
